# Generated by Django 2.2.1 on 2019-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(blank=True, max_length=255, null=True)),
                ('Trading_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Trading_Town_City', models.CharField(blank=True, max_length=255, null=True)),
                ('Trading_Post_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Registered_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Registered_Town_City', models.CharField(blank=True, max_length=255, null=True)),
                ('Registered_Post_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Website', models.URLField(blank=True, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('Company_Reg_Number_or_UTR', models.CharField(blank=True, max_length=255, null=True)),
                ('Your_Company_SIC_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Clusters_TTWA', models.CharField(blank=True, choices=[('GA', 'Guildford_and_Aldershot'), ('HW', 'High_Wycombe_and_Aylesbury'), ('RE', 'Reading'), ('SH', 'Slough_and_Heathrow')], max_length=5, null=True)),
                ('Company_Focus_Area', models.CharField(blank=True, choices=[('AS', 'Animation and SFX'), ('AC', 'AR / VR / MR Content'), ('AH', 'AR / VR / MR Hardware'), ('AU', 'Audio'), ('CS', 'Cultural Services'), ('DA', 'Digital Agency'), ('FT', 'Film / TV Production'), ('GA', 'Gaming'), ('JO', 'Journalism'), ('MA', 'Marketing Agency'), ('NG', 'Next Generation Technology'), ('OT', 'Other'), ('TL', 'Theatre / Life_Perf / Arts')], max_length=5, null=True)),
                ('Marginally_outside_cluster', models.CharField(blank=True, choices=[('YE', 'Yes'), ('NO', 'No')], max_length=5, null=True)),
                ('Unqualified_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Unqualified_Source', models.CharField(blank=True, max_length=255, null=True)),
                ('Street', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Province', models.CharField(blank=True, max_length=255, null=True)),
                ('Postal_Code', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, default='UK', max_length=255, null=True)),
                ('Last_Name', models.CharField(blank=True, default='n/a', max_length=255, null=True)),
                ('No_of_Employees', models.SmallIntegerField(blank=True, null=True)),
                ('Year_Company_Was_Founded', models.IntegerField(blank=True, null=True)),
                ('Unqualified_Owner', models.CharField(blank=True, default='Marianna Rolbina', max_length=255, null=True)),
                ('Unqualified_Owner_Id', models.IntegerField(blank=True, default='167499000000416001', null=True)),
            ],
        ),
    ]
