# Generated by Django 2.2.1 on 2019-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0002_auto_20190522_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohoinfo',
            name='Marginally_outside_cluster',
        ),
        migrations.AddField(
            model_name='zohoinfo',
            name='Within_Gateway_cluster',
            field=models.CharField(blank=True, choices=[('YE', 'Yes'), ('NO', 'No'), ('MA', 'Marginal')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='zohoinfo',
            name='Company_Focus_Area',
            field=models.CharField(blank=True, choices=[('AS', 'Animation and SFX'), ('AC', 'AR/VR/MR Content'), ('AH', 'AR/VR/MR Hardware'), ('AU', 'Audio'), ('CS', 'Cultural Services'), ('DA', 'Digital Agency'), ('FT', 'Film / TV Production'), ('GA', 'Gaming'), ('JO', 'Journalism'), ('MA', 'Marketing Agency'), ('NG', 'Next Generation Technology'), ('OT', 'Other'), ('TL', 'Theatre/Life_Perf/Arts')], max_length=5, null=True),
        ),
    ]
