# Generated by Django 2.2.1 on 2019-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crunch', '0003_auto_20190718_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoinfo',
            name='About_the_Company',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='zohoinfo',
            name='Cluster',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zohoinfo',
            name='Company_Focus_Area_Detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zohoinfo',
            name='Company_Generic_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='zohoinfo',
            name='Experience_in_immersive',
            field=models.CharField(blank=True, choices=[('NO', 'Novice'), ('IN', 'Intermediate'), ('EX', 'Expert')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='zohoinfo',
            name='Unqualified_type_Choice',
            field=models.CharField(blank=True, choices=[('ST', 'Sole Trader/Individual'), ('HE', 'HEI'), ('SM', 'SME'), ('IP', 'Industry Partner'), ('SO', 'Support Org')], max_length=5, null=True),
        ),
    ]
